---
- hosts: all
  remote_user: root

  tasks:
  - name: Test connection with a ping
    action: ping

  # Update all packages. Equivalent to "apt-get update"
  - apt: update_cache=yes
    become: true

  # Upgrade all packages. Equivalent to "apt-get upgrade"
  - apt: upgrade=yes
    become: true

  # Determine if 'Ansible' path exists and is a directory
  # Must test that both the directory exists and is also set to true
#  - stat: path=/home/pi/gitRepos
#    register: dirExists

  - debug: msg="Path exists and is a directory"
#    when: dirExists.stat.isdir is defined and dirExists.stat.isdir

  # Create the envmonitor directory
  - file: path=/home/pi/gitRepos/envmonitor state=directory mode=0755
    become: true

  # Clone the envmonitor git repo
  - include: tasks/envmonitor.yml
    become: true

  # Download and install all necessary Python modules to run sensors
#  - include: tasks/sensorInstall.yml
