# Install all Python sensor modules required for sensors 

---
  # Clone an Adafruit repo for testing
  - git: repo=https://github.com/adafruit/Adafruit_Python_SSD1306.git dest=/home/pi/womble/bomble update=yes

  # Install the module
  - easy_install: name=Adafruit_SSD1306
